# Generated by Django 6.0.2 on 2026-03-03 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='🎭', max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Animation Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('gltf_file', models.FileField(upload_to='animations/library/')),
                ('preview_gif', models.ImageField(blank=True, upload_to='animations/previews/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='animations/thumbs/')),
                ('duration_frames', models.PositiveIntegerField(default=0)),
                ('frame_rate', models.FloatField(default=30.0)),
                ('is_looping', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('is_user_uploaded', models.BooleanField(default=False)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('moderation_notes', models.TextField(blank=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_animations', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animations', to='users.userprofile')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animations', to='animations.animationcategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['moderation_status', 'is_public'], name='animations__moderat_aca50f_idx'), models.Index(fields=['category', 'is_public'], name='animations__categor_abf9bc_idx')],
            },
        ),
    ]
