# Generated by Django 6.0.2 on 2026-03-03 16:15

import apps.rigging.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiggedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to=apps.rigging.models.rig_upload_path)),
                ('original_format', models.CharField(max_length=8)),
                ('file_size_mb', models.FloatField(default=0)),
                ('rigged_glb', models.FileField(blank=True, upload_to=apps.rigging.models.rig_upload_path)),
                ('preview_thumbnail', models.ImageField(blank=True, upload_to=apps.rigging.models.rig_upload_path)),
                ('bone_mapping', models.JSONField(default=dict)),
                ('bone_corrections', models.JSONField(default=dict)),
                ('vertex_count', models.IntegerField(default=0)),
                ('bone_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('rig_log', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time_s', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rigs', to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='rigging_rig_user_id_e31f54_idx'), models.Index(fields=['status', 'created_at'], name='rigging_rig_status_9b7715_idx')],
            },
        ),
    ]
