# Generated by Django 5.1.4 on 2026-05-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigging', '0002_riggedmodel_detected_pose'),
    ]

    operations = [
        migrations.AddField(
            model_name='riggedmodel',
            name='landmarks',
            field=models.JSONField(blank=True, help_text='14 anatomical landmarks (chin, groin, L/R × {shoulder, elbow, wrist, hip, knee, ankle}) in three.js editor space, used to fit the rigify metarig to non-human-proportion meshes. Populated by auto-rig; editable via /landmarks/ + /rerig-landmarks/.', null=True),
        ),
    ]
