# Generated by Django 5.1.4 on 2026-05-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigging', '0003_riggedmodel_landmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='riggedmodel',
            name='detection_method',
            field=models.CharField(choices=[('geometry', 'Geometry only'), ('llm_vision', 'LLM vision + geometry refine'), ('user_landmarks', 'User-supplied landmarks'), ('failed', 'AI + geometry both failed; AABB defaults used')], db_index=True, default='geometry', help_text='Which path produced the landmarks attached to this rig.', max_length=24),
        ),
        migrations.AddField(
            model_name='riggedmodel',
            name='vision_response_raw',
            field=models.JSONField(blank=True, help_text="Raw validated response from the LLM vision provider, kept for debugging and audit. Null when detection_method is not 'llm_vision'.", null=True),
        ),
    ]
