# Generated by Django 5.1.4 on 2026-05-20 22:34

import apps.rigging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigging', '0004_riggedmodel_detection_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riggedmodel',
            name='landmark_debug_image',
            field=models.ImageField(blank=True, help_text='2x2 annotated render showing AI-detected vs final landmark positions. Populated only on the llm_vision path.', upload_to=apps.rigging.models.rig_upload_path),
        ),
    ]
