# Generated by Django 5.1.4 on 2026-06-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigging', '0005_riggedmodel_landmark_debug_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='riggedmodel',
            name='used_existing_rig',
            field=models.BooleanField(db_index=True, default=False, help_text='True when the upload already had a skeleton that skins the mesh; Rigify was skipped and the original rig kept.'),
        ),
        migrations.AlterField(
            model_name='riggedmodel',
            name='detection_method',
            field=models.CharField(choices=[('geometry', 'Geometry only'), ('llm_vision', 'LLM vision + geometry refine'), ('user_landmarks', 'User-supplied landmarks'), ('failed', 'AI + geometry both failed; AABB defaults used'), ('preserved', 'Original uploaded rig preserved')], db_index=True, default='geometry', help_text='Which path produced the landmarks attached to this rig.', max_length=24),
        ),
        migrations.AlterField(
            model_name='riggedmodel',
            name='landmarks',
            field=models.JSONField(blank=True, help_text='16 anatomical landmarks (chin, groin, L/R × {shoulder, elbow, wrist, hip, knee, ankle, heel}) in three.js editor space, used to fit the rigify metarig to non-human-proportion meshes. Populated by auto-rig; editable via /landmarks/ + /rerig-landmarks/.', null=True),
        ),
    ]
