# Generated by Django 5.1.4 on 2026-06-16 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigging', '0006_riggedmodel_used_existing_rig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('animation_ids', models.JSONField(default=list)),
                ('export_format', models.CharField(default='glb', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('output_file', models.FileField(blank=True, upload_to='exports/')),
                ('report', models.JSONField(blank=True, null=True)),
                ('cache_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='rigging.riggedmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
